### ISSUE TITLE
"Set vibrance only when program is in focus" feature keeps reseting

### ISSUE THREAD

**Issue by Jota-veh** [libvibrant/vibrantLinux#36]
Hi! i'm using manjaro xfce Qonos 21.2.4

The vibrant is working good, and the option to personalise apps are working good too, i'm using the "partial window title match" option.

the problem is: I always need to turn on the "Set vibrance only when program is in focus" option when the app starts. I'd like to use this without always need to configure.

anyway, thanks for this app! :)

**Comment by ademlabs** [comment]
I was going to file a report for this as well. I'm on Arch Linux and I have to keep setting that option back on all the time. It seems this value is not persisted.

**Comment by Scrumplex** [comment]
This should be fixed in b14d2bf60378f10bf48308b9bd68718651dbbf7c.

I pushed an update to Flathub and the AUR.

**Comment by Jota-veh** [comment]
Hi!
I didn't see the AUR update, it takes some time to see that?

**Comment by Scrumplex** [comment]
Oops. Maybe I forgot to actually push the changes 😅

**Comment by Scrumplex** [comment]
There we go: https://aur.archlinux.org/packages/vibrantlinux
