### ISSUE TITLE
Blank settings after relog/restart

### ISSUE THREAD

**Issue by frukbachers** [libvibrant/vibrantLinux#38]
I am aware that the project switched owners and that it's probably not maintained regularly but this is the only channel I can use to report this.

Behavior:
set up vibrantlinux to look for specific window, set saturation accordingly. see created entry, close/hide window, go into window and after 1 or 2 seconds saturation changes. after a restart this does not apply anymore and the entry is gone.

Expected behavior: 
same as above just that settings from before the relog/restart persist.

**Comment by Scrumplex** [comment]
Should be fixed with the newest version. It will take a few moments until it's published on Flathub

**Comment by frukbachers** [comment]
Thanks. Can confirm that settings persist now between sessions.
