### ISSUE TITLE
Added programs disappear

### ISSUE THREAD

**Issue by ademlabs** [libvibrant/vibrantLinux#41]
Adding a program and matching by title works for a while but from time to time all the profiles disappear and have to recreate them. Not sure how to debug.

**Comment by Scrumplex** [comment]
Can you confirm that you are running the latest version? There was a bug like this in #38

**Comment by Scrumplex** [comment]
My bad. I just checked and I forgot to actually push the AUR update. Now it should actually build the latest version where this was fixed (2.1.10)
