### ISSUE TITLE
Error when running ./update.sh

### ISSUE THREAD

**Issue by JaviruloNT** [libvibrant/vibrantLinux#47]
So, I get this when I try to run ./update.sh
![image](https://user-images.githubusercontent.com/110173052/182050059-eb743d45-5035-4637-94a6-d9c0bc4a6959.png)
I know it says "Already up to date", but it doesn't prompt any UI to use it.
I'm using PopOS 22.04, idk what other info I can give you (Yes, I installed libvibrant)

**Comment by JaviruloNT** [comment]
I managed to fix it, now it's this:
![image](https://user-images.githubusercontent.com/110173052/182051566-736bd109-51d9-4e42-8751-ca62053c55d7.png)

**Comment by JaviruloNT** [comment]
Note: https://github.com/libvibrant/libvibrant/issues/2

**Comment by Scrumplex** [comment]
I have dropped update.sh recently. Please use Flatpak or a distro package (if available)
