### ISSUE TITLE
error: libvibrant: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid

### ISSUE THREAD

**Issue by LethalManBoob** [libvibrant/vibrantLinux#48]
error: libvibrant: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid
:: File /var/cache/pacman/pkg/libvibrant-1.0.3-4-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

**Comment by Scrumplex** [comment]
This is a packaging issue on your end. From the signature I would assume you got it from Chaotic-AUR. I have no affiliation with them so if you have issues with it, please raise an issue there

**Comment by Scrumplex** [comment]
The error above clearly leads to Chatotic AUR though. That name and email address is from the maintainer of Chaotic-AUR

**Comment by LethalManBoob** [comment]
joseph@archlinux ~ % paru vibrantlinux
3 aur/vibrantlinux-git 2.1.7.r0.ga75092b-1 [+2 ~0.00]
    vibranceGUI replacement for Linux
2 aur/vibrantlinux 2.1.10-1 [+3 ~0.00]
    A tool to automate managing your screen's saturation depending on what programs are running
1 chaotic-aur/vibrantlinux 2.1.10-1 [0B 559.51KiB]
    A tool to automate managing your screen's saturation depending on what programs are running
:: Packages to install (eg: 1 2 3, 1-3):
:: 2
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Repo (1) libvibrant-1.0.3-4
Aur (1) vibrantlinux-2.1.10-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
:: Proceed with installation? [Y/n]: y
[sudo] password for joseph: 
resolving dependencies...
looking for conflicting packages...

Packages (1) libvibrant-1.0.3-4

Total Download Size:   0.03 MiB
Total Installed Size:  0.07 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...

09/20 17:06:22 [NOTICE] Downloading 1 item(s)

09/20 17:06:22 [NOTICE] CUID#7 - Redirecting to https://v.itstyrion.de/chaotic-aur/chaotic-aur/x86_64/libvibrant-1.0.3-4-x86_64.pkg.tar.zst

09/20 17:06:23 [NOTICE] Download complete: //var/cache/pacman/pkg/libvibrant-1.0.3-4-x86_64.pkg.tar.zst.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8a5d66|OK  |   2.8MiB/s|//var/cache/pacman/pkg/libvibrant-1.0.3-4-x86_64.pkg.tar.zst.part

Status Legend:
(OK):download completed.
(1/1) checking keys in keyring                               [--------------------------------] 100%
(1/1) checking package integrity                             [--------------------------------] 100%
error: libvibrant: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid
:: File /var/cache/pacman/pkg/libvibrant-1.0.3-4-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]

**Comment by Scrumplex** [comment]
Look at the log, it is downloading `https://v.itstyrion.de/chaotic-aur/chaotic-aur/x86_64/libvibrant-1.0.3-4-x86_64.pkg.tar.zst`

**Comment by Scrumplex** [comment]
You can try installing `libvibrant` manually first. Otherwise try to fix the Chaotic-AUR stuff. Maybe something is wrong with your keyring

**Comment by LethalManBoob** [comment]
I just went with the flatpak for now. but yeah ill take it up with chaotic at some point mb
