### ISSUE TITLE
Unable to open on Fedora 38

### ISSUE THREAD

**Issue by xplosionmind** [libvibrant/vibrantLinux#54]
I am now running Fedora 38. On the same device, this program opens from Ubuntu 22.10

**Comment by xplosionmind** [comment]
![Screenshot from 2023-04-17 09-42-14](https://user-images.githubusercontent.com/42862428/232418319-4b758e96-bee4-4016-91ea-b5c0c8ab449c.png)
![Screenshot from 2023-04-17 09-42-05](https://user-images.githubusercontent.com/42862428/232418323-244fede8-7759-40cb-a807-899f9e317172.png)

**Comment by Scrumplex** [comment]
Can you run it from a terminal? That would probably return an actual error message.

**Comment by xplosionmind** [comment]
Yes, sorry!
```
flatpak run io.github.libvibrant.vibrantLinux
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Gtk-Message: 18:10:11.054: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:10:11.054: Failed to load module "pk-gtk-module"
Gtk-Message: 18:10:11.054: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:10:11.054: Failed to load module "pk-gtk-module"
Qt: Session management error: Could not open network socket
terminate called after throwing an instance of 'std::runtime_error'
  what():  this system has no supported displays
```

**Comment by Scrumplex** [comment]
Hmm. Check issue #50

**Comment by xplosionmind** [comment]
I am using Wayland, and not X11… is it the same? What should I install manually?

I am sorry, I am no Linux expert 😬

**Comment by Scrumplex** [comment]
This sadly doesn't work on Wayland as there are no APIs to change these color correction values.

**Comment by xplosionmind** [comment]
Oh no! What alternative do you suggest?

Also: it might be I skimmed it too fast, but it does not appear to be specified in the README that this software is X11 only, maybe it is worth pointing out.

**Comment by Vilen23** [comment]
i am also facing the same issue anyone has a solution?

**Comment by frukto** [comment]
I got the same error on F38, even after changing back to X11

**Comment by Scrumplex** [comment]
The application now shows up if no outputs are supported with a message telling you about the issue.
